services:
  alfabet-api:
    build: .
    ports:
      - "8000:8000"
    links:
      - tensorflow
    # TODO: /root mount for cached model files
  tensorflow:
    image: tensorflow/serving
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_ENDPOINT
      - MODEL_BASE_PATH
      - MODEL_NAME
